import type { Metadata } from "next";
import { Josefin_Sans, Pacifico} from 'next/font/google'
import "./globle.css";

export const metadata: Metadata = {
  title: "Restaurant App",
  description: "Generated by next.js",
};

const josefin  = Josefin_Sans ({ weight: ['400', '600', '700'],  subsets: ['latin'] })
const pacifico  = Pacifico ({ weight: ['400'],  subsets: ['latin'] })


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${josefin.className} ${pacifico.className}`}>{children}</body>
    </html>
  );
}
